language: java
jdk:
  - openjdk17
before_install:
  - chmod +x mvnw
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:17-jdk-slim
script:
  - ./mvnw clean install
  - ./mvnw deploy jib:build -P deploy-docker